filebeat.inputs:
  - type: log
    paths:
      - /app/log.txt
    fields_under_root: true
    fields:
      host.name: "zapexample-${SERVER}"
    tags: ["${SERVER}"]

output.elasticsearch:
  hosts: ["http://${ELASTICSEARCH_HOST}:9200"]

setup.kibana:
  host: "http://${KIBANA_HOST}:5601"